import{a as h,S as p}from"./assets/vendor-Bfw2SXEy.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const w="45488141-0a4a6f9550d86e9b8ad8f4cbd",L="https://pixabay.com/api/";async function f(r,t=1,n=15){const s=`${L}?key=${w}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${n}`;try{return(await h.get(s)).data}catch{throw new Error("Network response was not ok")}}function y(r){const t=document.querySelector(".gallery"),n=r.map(s=>`
    <a href="${s.largeImageURL}">
      <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy"/>
      <div class="info">
        <p>Likes: ${s.likes}</p>
        <p>Views: ${s.views}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",n)}let g=new p(".gallery a");const b=document.querySelector("#search-form"),u=document.querySelector(".gallery"),i=document.querySelector(".loader"),l=document.querySelector(".load-more");let a="",c=1,m=0;b.addEventListener("submit",S);l.addEventListener("click",$);async function S(r){if(r.preventDefault(),a=r.currentTarget.elements.searchQuery.value.trim(),!a){iziToast.error({title:"Error",message:"Please enter a search term!"});return}u.innerHTML="",c=1,l.style.display="none";try{i.style.display="block";const t=await f(a,c);m=t.totalHits,t.hits.length===0?iziToast.warning({title:"Warning",message:"No images found!"}):(y(t.hits),g.refresh(),t.hits.length===15&&(l.style.display="block"))}catch(t){iziToast.error({title:"Error",message:`Something went wrong: ${t.message}`})}finally{i.style.display="none"}}async function $(){c+=1;try{i.style.display="block";const r=await f(a,c);y(r.hits),g.refresh(),u.children.length>=m&&(l.style.display="none",iziToast.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),window.scrollBy({top:u.firstElementChild.getBoundingClientRect().height*2,behavior:"smooth"})}catch(r){iziToast.error({title:"Error",message:`Something went wrong: ${r.message}`})}finally{i.style.display="none"}}
//# sourceMappingURL=commonHelpers.js.map
